/**
 * Maps each Wikimedia Commons filename used in the seed catalog to its
 * resolved, direct CDN URL (thumb.wikimedia.org / upload.wikimedia.org).
 *
 * Commons' `Special:FilePath` redirect is convenient (no need to know the
 * MD5 hash subdirectory) but resolves through the wiki application layer,
 * which rate-limits bursts of concurrent anonymous requests — exactly the
 * pattern a real page load produces (dozens of <img> tags mounting at once).
 * Resolving once at seed-authoring time and storing the final CDN URL here
 * means every real page load hits only the CDN, never the wiki app.
 */
export const COMMONS_IMAGE_MAP: Record<string, string> = {
  "8kg_kettlebell.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/8kg_kettlebell.jpg/960px-8kg_kettlebell.jpg",
  "A_desk_lamp.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/A_desk_lamp.jpg/960px-A_desk_lamp.jpg",
  "Air_Fryer_2020.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d3/Air_Fryer_2020.jpg/960px-Air_Fryer_2020.jpg",
  "Air_Fryer_5458.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0c/Air_Fryer_5458.jpg/960px-Air_Fryer_5458.jpg",
  "Average_Computer_Monitor.png": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/Average_Computer_Monitor.png/960px-Average_Computer_Monitor.png",
  "Backpacks_from_the_Habagat_Outdoor_Equipment_(2023-09-03).jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/Backpacks_from_the_Habagat_Outdoor_Equipment_%282023-09-03%29.jpg/960px-Backpacks_from_the_Habagat_Outdoor_Equipment_%282023-09-03%29.jpg",
  "Blue_alarm_clock_(3).jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Blue_alarm_clock_%283%29.jpg/960px-Blue_alarm_clock_%283%29.jpg",
  "Bluetooth_Speaker.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/72/Bluetooth_Speaker.jpg/960px-Bluetooth_Speaker.jpg",
  "Candle_in_candle_holder_(Unsplash).jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/94/Candle_in_candle_holder_%28Unsplash%29.jpg/960px-Candle_in_candle_holder_%28Unsplash%29.jpg",
  "Cast_Iron_Pan_1_2019-01-27.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a5/Cast_Iron_Pan_1_2019-01-27.jpg/960px-Cast_Iron_Pan_1_2019-01-27.jpg",
  "Cast-Iron-Pan.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/Cast-Iron-Pan.jpg/960px-Cast-Iron-Pan.jpg",
  "Charging_smartphone_with_powerbank_20180312.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/36/Charging_smartphone_with_powerbank_20180312.jpg/960px-Charging_smartphone_with_powerbank_20180312.jpg",
  "Close-up_Hand_holding_dumbbell_in_gym.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/Close-up_Hand_holding_dumbbell_in_gym.jpg/960px-Close-up_Hand_holding_dumbbell_in_gym.jpg",
  "Computer_monitor.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Computer_monitor.jpg/960px-Computer_monitor.jpg",
  "Cup188_(15644314231).jpg": "https://upload.wikimedia.org/wikipedia/commons/d/d6/Cup188_%2815644314231%29.jpg",
  "Cup222_(15623287766).jpg": "https://upload.wikimedia.org/wikipedia/commons/7/7a/Cup222_%2815623287766%29.jpg",
  "Desk_lamp.jpg": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Desk_lamp.jpg",
  "Digital-clock-alarm.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/eb/Digital-clock-alarm.jpg/960px-Digital-clock-alarm.jpg",
  "Electric-kettle.jpg": "https://upload.wikimedia.org/wikipedia/commons/7/78/Electric-kettle.jpg",
  "Elite_Wireless_Speaker.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Elite_Wireless_Speaker.jpg/960px-Elite_Wireless_Speaker.jpg",
  "French_press_2020.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/French_press_2020.jpg/960px-French_press_2020.jpg",
  "French_press.jpg": "https://upload.wikimedia.org/wikipedia/commons/9/91/French_press.jpg",
  "Heavy_Dumbbells_200_pound.JPG": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Heavy_Dumbbells_200_pound.JPG/960px-Heavy_Dumbbells_200_pound.JPG",
  "Kettlebell.JPG": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/Kettlebell.JPG/960px-Kettlebell.JPG",
  "Keychron_K4_mechanical_keyboard.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/aa/Keychron_K4_mechanical_keyboard.jpg/960px-Keychron_K4_mechanical_keyboard.jpg",
  "Keychron_K8_Non-Backlight_Wireless_Mechanical_Keyboard.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Keychron_K8_Non-Backlight_Wireless_Mechanical_Keyboard.jpg/960px-Keychron_K8_Non-Backlight_Wireless_Mechanical_Keyboard.jpg",
  "Metal_Water_Bottles.jpeg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/Metal_Water_Bottles.jpeg/960px-Metal_Water_Bottles.jpeg",
  "Microsoft_Wireless_Mouse_5000-3.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c5/Microsoft_Wireless_Mouse_5000-3.jpg/960px-Microsoft_Wireless_Mouse_5000-3.jpg",
  "Notebook.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Notebook.jpg/960px-Notebook.jpg",
  "Pen_on_a_notebook_(Unsplash).jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Pen_on_a_notebook_%28Unsplash%29.jpg/960px-Pen_on_a_notebook_%28Unsplash%29.jpg",
  "Power_bank.JPG": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7c/Power_bank.JPG/960px-Power_bank.JPG",
  "Reusable_Bag.jpg": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Reusable_Bag.jpg",
  "Scented_candle.png": "https://upload.wikimedia.org/wikipedia/commons/4/41/Scented_candle.png",
  "Sit-stand_desk.png": "https://upload.wikimedia.org/wikipedia/commons/3/30/Sit-stand_desk.png",
  "Smartwatch-828786.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Smartwatch-828786.jpg/960px-Smartwatch-828786.jpg",
  "Smartwatch.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Smartwatch.jpg/960px-Smartwatch.jpg",
  "Stainless_steel_water_bottle.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f4/Stainless_steel_water_bottle.jpg/960px-Stainless_steel_water_bottle.jpg",
  "Standing_Desk_by_Amrish_Kawa_06.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dc/Standing_Desk_by_Amrish_Kawa_06.jpg/960px-Standing_Desk_by_Amrish_Kawa_06.jpg",
  "Struggling_with_Overpacking_a_Full_Suitcase.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4a/Struggling_with_Overpacking_a_Full_Suitcase.jpg/960px-Struggling_with_Overpacking_a_Full_Suitcase.jpg",
  "Suitcase.jpg": "https://upload.wikimedia.org/wikipedia/commons/1/10/Suitcase.jpg",
  "Top_view_of_a_woman_stretching_on_a_yoga_mat.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2b/Top_view_of_a_woman_stretching_on_a_yoga_mat.jpg/960px-Top_view_of_a_woman_stretching_on_a_yoga_mat.jpg",
  "Tote_bag_blacu_tas_blacu.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Tote_bag_blacu_tas_blacu.jpg/960px-Tote_bag_blacu_tas_blacu.jpg",
  "Tropical_Rucksack_1.JPG": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/Tropical_Rucksack_1.JPG/960px-Tropical_Rucksack_1.JPG",
  "USB_webcam_for_PC.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/USB_webcam_for_PC.jpg/960px-USB_webcam_for_PC.jpg",
  "Webcam.JPG": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/Webcam.JPG/960px-Webcam.JPG",
  "White_electric_kettle.JPG": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/White_electric_kettle.JPG/960px-White_electric_kettle.JPG",
  "Wireless_mouse.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Wireless_mouse.jpg/960px-Wireless_mouse.jpg",
  "Yoga_mat.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/Yoga_mat.jpg/960px-Yoga_mat.jpg",
  "Sennheiser_HD_598_over-ear_headphones_(31514940057).jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/Sennheiser_HD_598_over-ear_headphones_%2831514940057%29.jpg/960px-Sennheiser_HD_598_over-ear_headphones_%2831514940057%29.jpg",
  "Harman_AKG_N20_headphones_.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/Harman_AKG_N20_headphones_.jpg/960px-Harman_AKG_N20_headphones_.jpg",
  "Velodyne's_vPulse_in-ear_headphones.jpg": "https://upload.wikimedia.org/wikipedia/commons/0/01/Velodyne%27s_vPulse_in-ear_headphones.jpg",
  "Latitude_Wireless_Earbuds.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/be/Latitude_Wireless_Earbuds.jpg/960px-Latitude_Wireless_Earbuds.jpg",
  "DAC_in_the_box.jpg": "https://upload.wikimedia.org/wikipedia/commons/0/0b/DAC_in_the_box.jpg",
  "Maurer_308_DAC.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/Maurer_308_DAC.jpg/960px-Maurer_308_DAC.jpg",
  "Little_Dot_MK_IV_Tube_Headphone_Amplifier_Pre-amplifier.jpg": "https://upload.wikimedia.org/wikipedia/commons/8/84/Little_Dot_MK_IV_Tube_Headphone_Amplifier_Pre-amplifier.jpg",
  "Rear_panel_of_audio_Hi-Fi_stereo_amplifier_Denon_PMA-980R.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Rear_panel_of_audio_Hi-Fi_stereo_amplifier_Denon_PMA-980R.jpg/960px-Rear_panel_of_audio_Hi-Fi_stereo_amplifier_Denon_PMA-980R.jpg",
  "Klotz_cables_RCA.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/Klotz_cables_RCA.jpg/960px-Klotz_cables_RCA.jpg",
  "One_white_RCA_connector_(plug,_male)_from_a_standard_RCA_cable_with_white_and_red_plugs_for_left_and_right.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/One_white_RCA_connector_%28plug%2C_male%29_from_a_standard_RCA_cable_with_white_and_red_plugs_for_left_and_right.jpg/960px-One_white_RCA_connector_%28plug%2C_male%29_from_a_standard_RCA_cable_with_white_and_red_plugs_for_left_and_right.jpg",
  "Aarong_leather_wallet.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Aarong_leather_wallet.jpg/960px-Aarong_leather_wallet.jpg",
  "An_old_wallet_with_brown_color.jpg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bd/An_old_wallet_with_brown_color.jpg/960px-An_old_wallet_with_brown_color.jpg",
};
